### ISSUE TITLE
Improve swap syntax

### ISSUE THREAD

**Issue by Yanqi-Xu** [irworkshop/accountability_datacleaning#10]
We often use this syntax in `swap`. But there're likely some problems returning false negatives, overwriting possible valid raw city fields. 
Here's an example.
`x <- tructure(list(first_name = c("Thomas", "Thomas", "Thomas", "Jenna", 
"Thomas", "Thomas", "Thomas", "Thomas", "Roosevelt", "Thomas", 
"Thomas", "Roosevelt"), last_name = c("Carpenter", "Carpenter", 
"Carpenter", "Liut", "Carpenter", "Carpenter", "Carpenter", "Carpenter", 
"Daniels", "Carpenter", "Carpenter", "Daniels"), registration_date = c("Jan 26 2012 10:29AM", 
"Jan 16 2013 12:20PM", "Jan 17 2014  2:49PM", "Nov 21 2014  2:11PM", 
"Jan 15 2015  4:47PM", "Jan 15 2016  2:41PM", "Jan  6 2017 12:07PM", 
"Jan 18 2018  2:02PM", "Nov 27 2017  4:37AM", "Jan 18 2019  3:15PM", 
"Jan  9 2020  2:21PM", "Feb  6 2020 10:39AM"), certification_number = c("L20120339", 
"L20130350", "L20140471", "L20140755", "L20150314", "L20160381", 
"L20170286", "L20180243", "L20170663", "L20190573", "L20200515", 
"L20200693"), client_name = c("United Transportation Union", 
"United Transportation Union", "United Transportation Union", 
"Mars, Incorporated", "United Transportation Union", "SMART-TRANSPORTATION DIVISION", 
"SMART-TRANSPORTATION DIVISION", "SMART-TRANSPORTATION DIVISION", 
"The Daniels Group", "SMART-TRANSPORTATION DIVISION", "SMART-TRANSPORTATION DIVISION", 
"Jackson Municipal Airport Authority"), address_line1 = c("PO BOX 3379", 
"PO BOX 3379", "PO BOX 3379", "30 Broad Street", "PO BOX 3379", 
"PO BOX 3379", "PO BOX 3379", "PO BOX 3379", "P.O. Box 8373", 
"PO BOX 3379", "PO BOX 3379", "P.O. Box 8373"), address_line2 = c("", 
"", "", "Suite 2603", "", "", "", "", "", "", "", ""), city = c("JACKSON", 
"JACKSON", "JACKSON", "New York", "JACKSON", "JACKSON", "JACKSON", 
"JACKSON", "Houston", "JACKSON", "JACKSON", "Houston"), state = c("MS", 
"MS", "MS", "NY", "MS", "MS", "MS", "MS", "MS", "MS", "MS", "MS"
), postal_code = c("Jackson", "Jackson", "Jackson", "10004", 
"Jackson", "Jackson", "Jackson", "Jackson", "77288", "Jackson", 
"Jackson", "77288"), telephone = c("601-948-0517", "601-948-0517", 
"601-948-0517", "212-471-0012", "601-948-0517", "601-948-0517", 
"601-948-0517", "601-948-0517", "601-832-4301", "601-948-0517", 
"601-948-0517", "601-832-4301"), dupe_flag = c(FALSE, FALSE, 
FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, 
FALSE), date = structure(c(15365, 15721, 16087, 16395, 16450, 
16815, 17172, 17549, 17497, 17914, 18270, 18298), class = "Date"), 
    year = c("2012", "2013", "2014", "2014", "2015", "2016", 
    "2017", "2018", "2017", "2019", "2020", "2020"), telephone_norm = c("(601) 948-0517", 
    "(601) 948-0517", "(601) 948-0517", "(212) 471-0012", "(601) 948-0517", 
    "(601) 948-0517", "(601) 948-0517", "(601) 948-0517", "(601) 832-4301", 
    "(601) 948-0517", "(601) 948-0517", "(601) 832-4301"), address_norm = c("PO BOX 3379", 
    "PO BOX 3379", "PO BOX 3379", "30 BROAD STREET SUITE 2603", 
    "PO BOX 3379", "PO BOX 3379", "PO BOX 3379", "PO BOX 3379", 
    "PO BOX 8373", "PO BOX 3379", "PO BOX 3379", "PO BOX 8373"
    ), zip5 = c(NA, NA, NA, "10004", NA, NA, NA, NA, "77288", 
    NA, NA, "77288"), city_norm = c("JACKSON", "JACKSON", "JACKSON", 
    "NEW YORK", "JACKSON", "JACKSON", "JACKSON", "JACKSON", "HOUSTON", 
    "JACKSON", "JACKSON", "HOUSTON")), row.names = c(NA, -12L
), class = "data.frame")` 
If we use the syntax ` x <- x %>% left_join(
    y = zipcodes,
    by = c(
      "state" = "state",
      "zip5" = "zip"
    )
  ) %>% 
  rename(city_match = city.y,
         city = city.x) %>% 
  mutate(
    match_abb = is_abbrev(city_norm, city_match),
    match_dist = str_dist(city_norm, city_match),
    city_swap = if_else(
      condition = match_abb | match_dist == 1,
      true = city_match,
      false = city_norm
    )
  ) %>% 
  select(
    -city_match,
    -match_dist,
    -match_abb
  )
` When match_dist is NA and in that case we don't want to change the original field, the condition  match_abb | match_dist == 1 will return NA, though in fact we want FALSE. We can consider using `condition = match_abb | match_dist == 1 & !is.na(match_dist)`

**Comment by k5cents** [comment]
Yeah I've actually just discovered that last week. You can see I already put the `!is.na()` call into the swap [in the template on line 371](https://github.com/irworkshop/accountability_datacleaning/blob/master/R_campfin/template_diary.Rmd#L371). Don't think it will be a huge problem, especially since we note the change in `prop_na()` at each stage and it only affects weird cities.

**Comment by Yanqi-Xu** [comment]
Great. On an unrelated note, I used normal_address() today but found that it was still using the full address Street instead of St. I just loaded the package yesterday. Any idea why?

**Comment by k5cents** [comment]
The changes only exist on the `abbrev` branch right now. I'll probably pull tomorrow.

```
remove.packages("campfin")
remotes::install_github("irworkshop/campfin", ref = "abbrev")
```

**Comment by Yanqi-Xu** [comment]
Sounds good. I'll close this. Thanks for the headsup.

**Comment by Yanqi-Xu** [comment]
I think for some reason using `condition = match_abb | match_dist == 1 & !is.na(match_dist)` does the job and using `!is.na(match_dist) & match_abb | match_dist == 1` won't do it in some of my files. I don't know why. Am I missing something here?
