### ISSUE TITLE
NV campaign finance missing addresses

### ISSUE THREAD

**Issue by jsfenfen** [irworkshop/accountability_datacleaning#2]
Hey @kiernann is it actually true that Nevada doesn't release any address information at all for contributors? It's not uncommon for states to not release the street address of a donor, and instead use just their city / state / zip. But Nevada data doesn't include a city or a state as near as I can tell? If that is the case, can you explicitly note this in the data diary page, I didn't see it.

Also, I'm really skeptical that they don't have addresses, they do appear on the sample pdf [here](https://github.com/irworkshop/accountability_datacleaning/blob/master/R_campfin/nv_contribs/docs/nv_example_report.pdf). I see that the payees tibble you're working with does not include this information, but that seems crazy that they won't disclose contributor city, contributor zip and contributor state.

**Comment by k5cents** [comment]
Unfortunately, yeah. I briefly noted this at the top of the [Explore section](https://github.com/irworkshop/accountability_datacleaning/tree/master/R_campfin/nv_contribs/docs/nv_diary_contribs.md#explore) of the diary.

When I first discovered the issue, I contacted the Public Information Officer at NV SOS and she had this to say:
> Currently, we do not have address data available in bulk data download. However, we are working to include it as we do get requests for this a lot. I am not sure of the time-frame, but I would imagine within the next year or so. For now, we just tell people they have to get the addresses from Aurora even though I know it is labor-intensive depending on the range of data you are looking at.

I spent a little while writing the [`extract_geo()`](https://github.com/irworkshop/accountability_datacleaning/tree/master/R_campfin/nv_contribs/code/extract_geo.R) function, which can pull the ZIP, etc from the HTML report pages. Unfortunately, it has to be run on each downloaded HTML page individually.

I can follow up with the NV SOS PIO and pressure them to get us some data. It's in the reports, so it's obviously in a database somewhere.

**Comment by jsfenfen** [comment]
Huh, we may want to examine how NV public records law views this. Lets ping @jlagetz and follow up offline.

**Comment by k5cents** [comment]
Actually fixed with 03c1b7c! :tada:
