### ISSUE TITLE
encoding in ME files

### ISSUE THREAD

**Issue by jsfenfen** [irworkshop/accountability_datacleaning#8]
Hi @kiernann I noticed that the file me_expends_clean (on S3, dated 10/3/19) is neither utf-8 or latin-1 encoded. The file command calls it `Non-ISO extended-ASCII text`. 

In general, I wanna load utf-8 or latin-1 files, but am kinda confused at how this ended up being neither. Do we need to add some sorta verification check that the output files really have a known encoding that they subscribe to?

**Comment by k5cents** [comment]
This is weird. It looks like all the yearly raw files are in different encodings, so R must have converted to the most basic shared encoding when I combined them.

```bash
$ file -i me/expends/data/raw/*
me/expends/data/raw/EXP_2008.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2009.csv.csv: text/plain; charset=us-ascii
me/expends/data/raw/EXP_2010.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2011.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2012.csv.csv: text/plain; charset=us-ascii
me/expends/data/raw/EXP_2013.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2014.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2015.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2016.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2017.csv.csv: text/plain; charset=unknown-8bit
me/expends/data/raw/EXP_2018.csv.csv: text/plain; charset=utf-8
me/expends/data/raw/EXP_2019.csv.csv: text/plain; charset=utf-8
```

The [`readr::write_csv()`](https://readr.tidyverse.org/reference/write_delim.html) function we use _should_ convert to UTF-8 when writing to disc:
> **All columns are encoded as UTF-8.** `write_excel_csv()` and `write_excel_csv2()` also include a UTF-8 Byte order mark which indicates to Excel the csv is UTF-8 encoded.

For some reason, it's won't in this case. It's saving it as that "unknown 8-bit" encoding. There must be some whacky character somewhere in the file. I can convert to ASCII using `iconv`, but there's some bus error and it stops before UTF-8.

```bash
$ file -i *
me_expends_clean.csv: text/plain; charset=unknown-8bit
$ iconv -t UTF-8//TRANSLIT me_expends_clean.csv -o me_expends_clean.csv 
Bus error (core dumped)
$ file -i *
me_expends_clean.csv: text/plain; charset=us-ascii
```

I'll keep messing around and see if I can get UTF-8 on S3.

**Comment by k5cents** [comment]
Scratch that, I found a way around the bus error in `iconv` and managed to convert to UTF-8.

```bash
$ file -i *
me_expends_clean.csv: text/plain; charset=utf-8
```

 I know @jlagetz had mentioned to hold off uploading to S3 for a few days, do you want this converted file up there now?

**Comment by jsfenfen** [comment]
Awesome, thx @kiernann, if you just throw it up there now--ideally with the same file name as the one it replaces--that would be great. (was working on an elasticsearch migration + update, it's all good now).
